---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
    exclude_patterns:
    - "!**.md"
checks:
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
- "*/"
- "!lib/**/*"
- "!index.js"
