language: node_js
matrix:
  include:
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME=chrome
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME=firefox
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME="internet explorer"
    - node_js: "8"
      env: NO_SAUCE=true
    - node_js: "7"
      env: NO_SAUCE=true
env: 
  global:
    - SAUCE_USERNAME=Gerkin
    - SAUCE_ACCESS_KEY=bcc962ee-af76-4e36-bf15-ce3cbbbb5b8c
notifications:
  slack:
    rooms:
      - altenter-project:Pc8sMyCuHNPBCg1TOw0weD9S#tech
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
cache:
  directories:
    - "node_modules"