language: node_js
matrix:
  include:
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME=chrome
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME=firefox
    - node_js: "node"
      addons:
        sauce_connect: true
      env:
        - SAUCE_ONLY=true
        - BROWSER_NAME="internet explorer"
    - node_js: "8"
      env: NO_SAUCE=true
    - node_js: "7"
      env: NO_SAUCE=true
    - node_js: "6"
      env: NO_SAUCE=true
env: 
  global:
    - CC_TEST_REPORTER_ID=44a8b1ae86577092040904da4ac5c76afd29648333c2ad4039e7622a90800745
    - SAUCE_USERNAME=Gerkin
    - SAUCE_ACCESS_KEY=bcc962ee-af76-4e36-bf15-ce3cbbbb5b8c
notifications:
  slack:
    rooms:
      - altenter-project:Pc8sMyCuHNPBCg1TOw0weD9S#tech
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"